//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSSDemoWebForms
{


    public partial class Unsafe
    {

        protected global::System.Web.UI.WebControls.TextBox txtInput;
        protected global::System.Web.UI.WebControls.Button btnRender;
        protected global::System.Web.UI.WebControls.Literal litRaw;
        protected global::System.Web.UI.WebControls.Literal litAttr;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
